// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDte7zV9zij43hI_oWO6UdKvrgGCiWmQDE',
    appId: '1:1060272536183:web:6cedea283679241c536472',
    messagingSenderId: '1060272536183',
    projectId: 'final-e9259',
    authDomain: 'final-e9259.firebaseapp.com',
    storageBucket: 'final-e9259.appspot.com',
    measurementId: 'G-FRETWF8BFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB3UOz6Z46mvBwqk49H_n4f4fZr_GSGOQ',
    appId: '1:1060272536183:android:4a5bfe8d7e349b85536472',
    messagingSenderId: '1060272536183',
    projectId: 'final-e9259',
    storageBucket: 'final-e9259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVn4NbA02gBmqAPCWWzo931MwO-NRfZ3k',
    appId: '1:1060272536183:ios:11a00e570ef0ced2536472',
    messagingSenderId: '1060272536183',
    projectId: 'final-e9259',
    storageBucket: 'final-e9259.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVn4NbA02gBmqAPCWWzo931MwO-NRfZ3k',
    appId: '1:1060272536183:ios:b090dc666cd9669b536472',
    messagingSenderId: '1060272536183',
    projectId: 'final-e9259',
    storageBucket: 'final-e9259.appspot.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
